apiVersion: v1
kind: Service
metadata:
  name: admin-api-service
spec:
  selector:
    app: admin-api
  type: ClusterIP
  ports:
    - name: admin-api-service
      port: 80
      targetPort: 80
      protocol: TCP