logging:
  level:
    ROOT: INFO
  include-application-name: false
  pattern:
    correlation: '[%X{X-Trace-Id:-}]'

server:
  port: ${PORT:8082}
  servlet:
    context-path: /access/api

spring:
  application:
    name: access-service
  messages:
    basename: i18n/messages
    encoding: UTF-8
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_01?currentSchema=ms_access
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 50
        order_inserts: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: 'none'
  liquibase:
    enabled: false
    default-schema: ms_access
    change-log: classpath:db/changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/ms-poc-realm/protocol/openid-connect/certs

---

spring:
  config:
    activate:
      on-profile: "cloud"
  datasource:
    url: jdbc:postgresql://postgres_db:5432/db_01?currentSchema=ms_access
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/ms-poc-realm/protocol/openid-connect/certs

server:
  servlet:
    context-path: /