version: '3.1'
services:
  user-api:
    container_name: 'user-api'
    image: 'dev/user-api:v1'
    build: '.'
    ports:
      - 8081:8081
    networks:
      - local-network
networks:
  local-network:
    name: local-network