apiVersion: v1
kind: Service
metadata:
  name: user-api-service
  labels:
    spring-boot: "true"
spec:
  selector:
    app: user-api # nome do pod
  ports:
    - name: http
      port: 80
      targetPort: 80 #porta do container
      protocol: TCP