apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  selector:
    app: user-api # nome do pod
  type: ClusterIP
  ports:
    - name: user-api-service
      port: 80
      targetPort: 80 #porta do container
      protocol: TCP